In [12]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/job-description-dataset/job_descriptions.csv

In [13]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [14]:
df=pd.read_csv("/kaggle/input/job-description-dataset/job_descriptions.csv")
df.head(2)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,2022-04-24,Female,Brandon Cunningham,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,2022-12-19,Female,Francisco Larsen,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."

In [15]:
print(f'The dataset has {df.shape[0]} rows and {df.shape[1]} columns.')
# df.shape

The dataset has 1615940 rows and 23 columns.

In [16]:
print(f'The dataset has {df.isna().sum().sum()} null values.')

The dataset has 5478 null values.

In [17]:
df.dropna(inplace=True)

In [18]:
print(f'The dataset has {df.isna().sum().sum()} null values.')

The dataset has 0 null values.

In [19]:
print(f'The dataset has {df.duplicated().sum()} duplicate values.')

The dataset has 0 duplicate values.

In [20]:
print('List Of Columns:\n',df.columns)

List Of Columns:
 Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [21]:
print('Statistical Summary:\n',df.describe())

Statistical Summary:
              Job Id      latitude     longitude  Company Size
count  1.610462e+06  1.610462e+06  1.610462e+06  1.610462e+06
mean   1.548978e+15  1.937873e+01  1.640275e+01  7.370378e+04
std    8.946738e+14  2.355602e+01  7.066469e+01  3.529832e+04
min    1.817948e+11 -4.090060e+01 -1.751982e+02  1.264600e+04
25%    7.740660e+14  5.152100e+00 -1.518040e+01  4.311400e+04
50%    1.547972e+15  1.807080e+01  1.914510e+01  7.363350e+04
75%    2.323738e+15  3.907420e+01  4.757690e+01  1.042990e+05
max    3.099618e+15  7.170690e+01  1.780650e+02  1.348340e+05

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1610462 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1610462 non-null  int64
 1   Experience        1610462 non-null  object
 2   Qualifications    1610462 non-null  object
 3   Salary Range      1610462 non-null  object
 4   location          1610462 non-null  object
 5   Country           1610462 non-null  object
 6   latitude          1610462 non-null  float64
 7   longitude         1610462 non-null  float64
 8   Work Type         1610462 non-null  object
 9   Company Size      1610462 non-null  int64
 10  Job Posting Date  1610462 non-null  object
 11  Preference        1610462 non-null  object
 12  Contact Person    1610462 non-null  object
 13  Contact           1610462 non-null  object
 14  Job Title         1610462 non-null  object
 15  Role              1610462 non-null  object
 16  Job Portal        1610462 non-null  object
 17  Job Description   1610462 non-null  object
 18  Benefits          1610462 non-null  object
 19  skills            1610462 non-null  object
 20  Responsibilities  1610462 non-null  object
 21  Company           1610462 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 294.9+ MB

In [24]:
df.to_csv('mycsvfile.csv',index=False)